// Which of the files on disk belong in a debug dump.
//
// `clips/` and `captures/` are not emptied between runs, so by the afternoon
// they hold everything that has ever happened on that laptop. A dump is about
// one session — the one somebody is asking about — and sending a hundred and
// forty megabytes of last week with it helps nobody.
//
// The session's own bookmarks decide: a clip belongs if an angle points at it,
// and a capture belongs if it was written for one of these bookmarks.

import type { Bookmark } from './bookmarks.js';
import { captureIdPrefix } from './capture.js';
import { isSafeClipName } from './state.js';

const CLIPS_URL = '/clips/';

/** The clip files this session's bookmarks actually point at. */
export function clipsInUse(bookmarks: readonly Bookmark[]): string[] {
  const wanted = new Set<string>();
  for (const bookmark of bookmarks) {
    for (const angle of bookmark.angles) {
      if (!angle.url?.startsWith(CLIPS_URL)) continue;
      const name = angle.url.slice(CLIPS_URL.length);
      // These names become paths on whoever opens the archive. They have only
      // ever been generated by us, so anything else is refused rather than fixed.
      if (isSafeClipName(name)) wanted.add(name);
    }
  }
  return [...wanted];
}

/**
 * The capture files written for this session's bookmarks.
 *
 * Matched on the name rather than by opening each one: `captureName` puts the
 * bookmark's first characters in the middle of it, and reading a few hundred
 * records to learn what their names already say would be work for nothing.
 */
export function capturesInUse(bookmarks: readonly Bookmark[], names: readonly string[]): string[] {
  const prefixes = new Set(bookmarks.map((bookmark) => captureIdPrefix(bookmark.id)));
  return names.filter((name) => {
    const parts = name.replace(/\.(json|bin)$/, '').split('_');
    return parts.length === 3 && name !== parts.join('_') && prefixes.has(parts[1]!);
  });
}
